clone_depth: 1
version: '{branch}-{build}'
image: Visual Studio 2019
test: off
build_script:
  - cmd: dotnet tool restore
  - cmd: dotnet build osu.Server.sln -c:Release
  - cmd: dotnet jb inspectcode "osu.Server.sln" --output="temp/inspectcodereport.xml" --caches-home="temp/inspectcode" --verbosity=WARN
  - cmd: dotnet nvika parsereport "temp/inspectcodereport.xml" --treatwarningsaserrors